// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemZaZaposlenike.Data;

#nullable disable

namespace SistemZaZaposlenike.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414200813_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemZaZaposlenike.Models.Odjel", b =>
                {
                    b.Property<int>("OdjelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OdjelID"));

                    b.Property<string>("Lokacija")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OdjelID");

                    b.ToTable("Odjeli");

                    b.HasData(
                        new
                        {
                            OdjelID = 1,
                            Lokacija = "Sarajevo",
                            Naziv = "IT"
                        },
                        new
                        {
                            OdjelID = 2,
                            Lokacija = "Sarajevo",
                            Naziv = "HR"
                        },
                        new
                        {
                            OdjelID = 3,
                            Lokacija = "Sarajevo",
                            Naziv = "Finance"
                        });
                });

            modelBuilder.Entity("SistemZaZaposlenike.Models.Projekat", b =>
                {
                    b.Property<int>("ProjekatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjekatID"));

                    b.Property<decimal?>("BudzetUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DatumKraj")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumPocetak")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProjekatID");

                    b.ToTable("Projekti");

                    b.HasData(
                        new
                        {
                            ProjekatID = 1,
                            BudzetUSD = 15000m,
                            DatumKraj = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumPocetak = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naziv = "Web App"
                        },
                        new
                        {
                            ProjekatID = 2,
                            BudzetUSD = 22000m,
                            DatumKraj = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumPocetak = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naziv = "Mobile App"
                        },
                        new
                        {
                            ProjekatID = 3,
                            BudzetUSD = 18000m,
                            DatumKraj = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumPocetak = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naziv = "API System"
                        },
                        new
                        {
                            ProjekatID = 4,
                            BudzetUSD = 12000m,
                            DatumKraj = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumPocetak = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naziv = "Internal Tool"
                        });
                });

            modelBuilder.Entity("SistemZaZaposlenike.Models.Zaposlenik", b =>
                {
                    b.Property<int>("ZaposlenikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZaposlenikID"));

                    b.Property<DateTime>("DatumZaposlenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OdjelID")
                        .HasColumnType("int");

                    b.Property<decimal>("PlataMonthly")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ZaposlenikID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OdjelID");

                    b.ToTable("Zaposlenici");

                    b.HasData(
                        new
                        {
                            ZaposlenikID = 1,
                            DatumZaposlenja = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kerim@test.com",
                            Ime = "Kerim",
                            OdjelID = 1,
                            PlataMonthly = 2000m,
                            Prezime = "Celjo"
                        },
                        new
                        {
                            ZaposlenikID = 2,
                            DatumZaposlenja = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amir@test.com",
                            Ime = "Amir",
                            OdjelID = 1,
                            PlataMonthly = 1800m,
                            Prezime = "Hodzic"
                        },
                        new
                        {
                            ZaposlenikID = 3,
                            DatumZaposlenja = new DateTime(2023, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lejla@test.com",
                            Ime = "Lejla",
                            OdjelID = 2,
                            PlataMonthly = 1700m,
                            Prezime = "Kovacevic"
                        },
                        new
                        {
                            ZaposlenikID = 4,
                            DatumZaposlenja = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara@test.com",
                            Ime = "Sara",
                            OdjelID = 2,
                            PlataMonthly = 1600m,
                            Prezime = "Basic"
                        },
                        new
                        {
                            ZaposlenikID = 5,
                            DatumZaposlenja = new DateTime(2023, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "adnan@test.com",
                            Ime = "Adnan",
                            OdjelID = 3,
                            PlataMonthly = 2200m,
                            Prezime = "Suljic"
                        },
                        new
                        {
                            ZaposlenikID = 6,
                            DatumZaposlenja = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "haris@test.com",
                            Ime = "Haris",
                            OdjelID = 3,
                            PlataMonthly = 2100m,
                            Prezime = "Delic"
                        },
                        new
                        {
                            ZaposlenikID = 7,
                            DatumZaposlenja = new DateTime(2024, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maja@test.com",
                            Ime = "Maja",
                            OdjelID = 1,
                            PlataMonthly = 1900m,
                            Prezime = "Ilic"
                        },
                        new
                        {
                            ZaposlenikID = 8,
                            DatumZaposlenja = new DateTime(2023, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivan@test.com",
                            Ime = "Ivan",
                            OdjelID = 2,
                            PlataMonthly = 1750m,
                            Prezime = "Peric"
                        },
                        new
                        {
                            ZaposlenikID = 9,
                            DatumZaposlenja = new DateTime(2024, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amina@test.com",
                            Ime = "Amina",
                            OdjelID = 3,
                            PlataMonthly = 1650m,
                            Prezime = "Smajic"
                        },
                        new
                        {
                            ZaposlenikID = 10,
                            DatumZaposlenja = new DateTime(2024, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nermin@test.com",
                            Ime = "Nermin",
                            OdjelID = 1,
                            PlataMonthly = 2000m,
                            Prezime = "Zukic"
                        });
                });

            modelBuilder.Entity("SistemZaZaposlenike.Models.ZaposlenikProjekat", b =>
                {
                    b.Property<int>("ZaposlenikID")
                        .HasColumnType("int");

                    b.Property<int>("ProjekatID")
                        .HasColumnType("int");

                    b.Property<int>("SatiNaTjednu")
                        .HasColumnType("int");

                    b.Property<string>("Uloga")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ZaposlenikID", "ProjekatID");

                    b.HasIndex("ProjekatID");

                    b.ToTable("ZaposlenikProjekti");

                    b.HasData(
                        new
                        {
                            ZaposlenikID = 1,
                            ProjekatID = 1,
                            SatiNaTjednu = 40,
                            Uloga = "Developer"
                        },
                        new
                        {
                            ZaposlenikID = 2,
                            ProjekatID = 1,
                            SatiNaTjednu = 35,
                            Uloga = "Backend"
                        },
                        new
                        {
                            ZaposlenikID = 3,
                            ProjekatID = 2,
                            SatiNaTjednu = 20,
                            Uloga = "HR Support"
                        },
                        new
                        {
                            ZaposlenikID = 4,
                            ProjekatID = 3,
                            SatiNaTjednu = 25,
                            Uloga = "QA"
                        },
                        new
                        {
                            ZaposlenikID = 5,
                            ProjekatID = 4,
                            SatiNaTjednu = 30,
                            Uloga = "Finance Lead"
                        });
                });

            modelBuilder.Entity("SistemZaZaposlenike.Models.Zaposlenik", b =>
                {
                    b.HasOne("SistemZaZaposlenike.Models.Odjel", "Odjel")
                        .WithMany("Zaposlenici")
                        .HasForeignKey("OdjelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Odjel");
                });

            modelBuilder.Entity("SistemZaZaposlenike.Models.ZaposlenikProjekat", b =>
                {
                    b.HasOne("SistemZaZaposlenike.Models.Projekat", "Projekat")
                        .WithMany("ZaposlenikProjekti")
                        .HasForeignKey("ProjekatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemZaZaposlenike.Models.Zaposlenik", "Zaposlenik")
                        .WithMany("ZaposlenikProjekti")
                        .HasForeignKey("ZaposlenikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projekat");

                    b.Navigation("Zaposlenik");
                });

            modelBuilder.Entity("SistemZaZaposlenike.Models.Odjel", b =>
                {
                    b.Navigation("Zaposlenici");
                });

            modelBuilder.Entity("SistemZaZaposlenike.Models.Projekat", b =>
                {
                    b.Navigation("ZaposlenikProjekti");
                });

            modelBuilder.Entity("SistemZaZaposlenike.Models.Zaposlenik", b =>
                {
                    b.Navigation("ZaposlenikProjekti");
                });
#pragma warning restore 612, 618
        }
    }
}
