// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemZaZaposlenike.Data;

#nullable disable

namespace SistemZaZaposlenike.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414194514_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemZaZaposlenike.Models.Odjel", b =>
                {
                    b.Property<int>("OdjelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OdjelID"));

                    b.Property<string>("Lokacija")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OdjelID");

                    b.ToTable("Odjeli");
                });

            modelBuilder.Entity("SistemZaZaposlenike.Models.Projekat", b =>
                {
                    b.Property<int>("ProjekatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjekatID"));

                    b.Property<decimal?>("BudzetUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DatumKraj")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumPocetak")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProjekatID");

                    b.ToTable("Projekti");
                });

            modelBuilder.Entity("SistemZaZaposlenike.Models.Zaposlenik", b =>
                {
                    b.Property<int>("ZaposlenikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZaposlenikID"));

                    b.Property<DateTime>("DatumZaposlenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OdjelID")
                        .HasColumnType("int");

                    b.Property<decimal>("PlataMonthly")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ZaposlenikID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OdjelID");

                    b.ToTable("Zaposlenici");
                });

            modelBuilder.Entity("SistemZaZaposlenike.Models.ZaposlenikProjekat", b =>
                {
                    b.Property<int>("ZaposlenikID")
                        .HasColumnType("int");

                    b.Property<int>("ProjekatID")
                        .HasColumnType("int");

                    b.Property<int>("SatiNaTjednu")
                        .HasColumnType("int");

                    b.Property<string>("Uloga")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ZaposlenikID", "ProjekatID");

                    b.HasIndex("ProjekatID");

                    b.ToTable("ZaposlenikProjekti");
                });

            modelBuilder.Entity("SistemZaZaposlenike.Models.Zaposlenik", b =>
                {
                    b.HasOne("SistemZaZaposlenike.Models.Odjel", "Odjel")
                        .WithMany("Zaposlenici")
                        .HasForeignKey("OdjelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Odjel");
                });

            modelBuilder.Entity("SistemZaZaposlenike.Models.ZaposlenikProjekat", b =>
                {
                    b.HasOne("SistemZaZaposlenike.Models.Projekat", "Projekat")
                        .WithMany("ZaposlenikProjekti")
                        .HasForeignKey("ProjekatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemZaZaposlenike.Models.Zaposlenik", "Zaposlenik")
                        .WithMany("ZaposlenikProjekti")
                        .HasForeignKey("ZaposlenikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projekat");

                    b.Navigation("Zaposlenik");
                });

            modelBuilder.Entity("SistemZaZaposlenike.Models.Odjel", b =>
                {
                    b.Navigation("Zaposlenici");
                });

            modelBuilder.Entity("SistemZaZaposlenike.Models.Projekat", b =>
                {
                    b.Navigation("ZaposlenikProjekti");
                });

            modelBuilder.Entity("SistemZaZaposlenike.Models.Zaposlenik", b =>
                {
                    b.Navigation("ZaposlenikProjekti");
                });
#pragma warning restore 612, 618
        }
    }
}
